development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: logophone
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: logophone_test
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: logophone
  pool: 5
  username: root
  password: ctrhtnfhbfn
  socket: /var/run/mysqld/mysqld.sock